backup:
  .bashrc
  .bash_profile
  .bash_login
  .bash_logout
  .histfile
  .profile
  .zshrc
  .zlogin
  .zsh_history
  .zsh-update
  .gemrc
  .gitconfig

install:
  - git

link:
  ~/.gitconfig: config/git/.gitconfig
  
  ~/.bashrc: config/bash/.bashrc
  ~/.bash_profile: config/bash/.bash_profile
  ~/.profile: config/bash/.profile

  ~/.zshrc: config/zsh/.zshrc

  ~/.nanorc: config/editors/.nanorc

  ~/.gemrc: config/extras/.gemrc

sublime:
  config_path: "~/.config/sublime-text-3/Packages/User/"
  package: sublime-text
  which_package: subl

git:
  github:
    create_key: True
    key_size: 4096
    add_to_config: True
  
  bitbucket:
    create_key: True
    key_size: 4096
    add_to_config: True

  create_config_file: True
