backup:
  .bashrc
  .bash_profile
  .bash_login
  .bash_logout
  .histfile
  .profile
  .zshrc
  .zlogin
  .zsh_history
  .zsh-update
  .gemrc
  .gitconfig

install:
  - git

link:
  ~/.gitconfig: config/git/.gitconfig
  
  ~/.bashrc: config/bash/.bashrc
  ~/.bash_profile: config/bash/.bash_profile
  ~/.profile: config/bash/.profile

  ~/.zshrc: config/zsh/.zshrc

  ~/.nanorc: config/editors/.nanorc

  ~/.gemrc: config/extras/.gemrc

#  "~/Desktop/sublime-text/":
#    path: subl-config
#    create: true

sublime:
  install: true
  config_path: "~/.config/sublime-text-3/Packages/User/"
  package: sublime-text
  which_package: subl
